### PR TITLE
benchmarks: keep db in memory for eventstore benchmark

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by lewurm** [comment]
see #25

**Comment by lewurm** [comment]
@schani what do you think?  we might get different (hopefully more stable) results on that benchmark.

**Comment by schani** [comment]
The results on eventstore are pretty stable.

If we have enough history to go back and redo the results where eventstore was faster (see http://xamarin.github.io/benchmarker/front-end/compare.html#ids=1146+1157) then we should switch.  If the results are the same with these flags on, even better, then we won't have to redo anything.

**Comment by lewurm** [comment]
This should also include disabling the logs in `NLog.config`. @vkargov do you know how to do that?

**Comment by vkargov** [comment]
@lewurm: https://github.com/xamarin/benchmarker/pull/27

Also, I ran Eventstore with disabled logs and enabled in-memory database and compared against the current configuration: http://xamarin.github.io/benchmarker/front-end/compare.html#ids=1662+1663. Which means the test will be running 3+ faster, meaning the old data for the test will be "invalid".

I do, however, believe, that the change should be made, since we should primarily be concerned with actual cpu/memory performance, and not as much with hard drive I/O and the way how optimally Linux handles it.

**Comment by schani** [comment]
Would you mind also testing it against mono before the thread-parking change that made it slower?  I.e. commit 778adf07692178a56fffa34f4b50df13a6074e6e?

**Pull request merged**
