### PR TITLE
Add the Gosharp benchmark composed of 4 Go benchmarks compiled into CIL

### PR DESCRIPTION
**Pull request by vkargov**
In the current configuration 4 benchmarks are called that seemed most "interesting" to me and did not take too much time for execution. (performance is generally a significant issue of this experimental Tardis/Haxe toolchain that was used to obtain the CIL assemblies).

### CODE REVIEW

**Comment by lewurm** [comment]
can you split up the suite? instead of tracking one collection of benchmarks, it would be nicer to track each single benchmark. i.e. instead of having a single `gosharp` benchmark, split it up into `gosharp-fannkuch11`, `gosharp-goparse`, `gosharp-mandelbrot200`, ...

**Comment by vkargov** [comment]
I don't think that would be a very good move considering that the majority of time in these tests is spent on emulating the semantics of Go and Haxe (conversions, initializations, etc) which is nearly identical for all the 4 tests.
If I made several separate tests, their performance would most likely change in the same way upon every commit to the runtime, and they could add some bias to the overall geomean performance stat among all the tests favouring this pretty special case. In my understanding, that would not be a good thing, and go against the general spirit of the suite where each benchmark is supposed to represent a practically interesting, but fairly unique in its execution pattern, workload.
All that said, if there was a possibility to specify some "weight" to a benchmark that would indicate how much its result should contribute to the global performance stat, I would do exactly that, split it into 4 separate suites and add the weight of 0.25 to each, so that they would contribute as just 1 test as a whole to the overall geomean. Perhaps I should do exactly that? (@schani?)

**Comment by schani** [comment]
I'm fine with this being a single test.  I'm guessing the tests test mostly the same thing - the translation overhead from Go to CIL.

**Comment by vkargov** [comment]
Yes, it should be mostly the same thing, and that's why I don't think there is much sense to split it into multiple separate benchmarks.
I don't think we would lose much if we included only one test either, but just to be sure and get a more look on it, I've made a collection of 4 smaller ones.

**Comment by lewurm** [comment]
following that logic, we also only need one C# benchmark too, because hey,
the translation process is the same for every benchmark :-)

tracking each benchmark on its own doesn't hurt in terms of data, and we
might be interested in it at some point for _some_ reason (e.g., remember
that cache line regression on ARM recently?). If we pull it together to one
suite we're going to have a similar mess as with msbiology right now: it's
flaky all the time and no one knows why.

If the geomean is not representative anymore because of that, we can always
change how we compute that; it's just a view on the database.

**Comment by vkargov** [comment]
> following that logic, we also only need one C# benchmark too, because hey, the translation process is the same for every benchmark :-)
I'm not sure there is much similarity. Mcs, as well as csc, compile C# into CIL _directly_, without any intermediate steps (except for the internal IR specifically crafted for the purpose of efficient code generation, of course), and are tuned for producing optimal code that would (hopefully!) be good enough to spend most of the time on the actual algorithm.
What we've got here, instead of that, is first Tardis/Go converting Go code into Haxe by emulating the Go semantics in Haxe (producing more than a 1000 not-so-well-optimized files for different classes from the source code and the standard library!), and then, on top of that, Haxe emulating the semantics of C# on top of that mess. While what we get in the end is not quite an interpreter running an interpreter of a language, it's dangerously close to being that.
So instead of C#, I'd compare it to the IronPython test that we already have in the suite that runs 8 separate routines, which, nonetheless, are not split into 8 separate benchmarks, with IronPython bundled with each one of them.

> tracking each benchmark on its own doesn't hurt in terms of data
I agree, it would be the best way to handle that, as I mentioned, *provided* we add support for specifying custom weights for the global geomean number.

> If the geomean is not representative anymore because of that, we can always change how we compute that; it's just a view on the database.
I do believe it would be less representative if I go ahead and include multiple benchmarks. Which, as I mentioned, could be amended by adding an option to specify different weights for each test in the suite, and not treat them as equals. These several highly experimental benchmark should NOT overshadow the performance results we get with fsharp, or roslyn, or ironpython/js, or any other important test.

**Comment by schani** [comment]
Yeah, Bernhard is right.  Let's split them up.

Vladimir, could you rebase the commits when you push the split up pull request?  Just to make Jenkins happy.

**Comment by lewurm** [comment]
I see that it's not like mcs, but more like ironpython/ironjs. that we have
ironpython/ironjs in a single benchmark is already a mistake imho, but once
started it isn't easy to change.

again, we can always change how we compute the mean on the front page as
you suggested, but we can't (easily) get the data for each single benchmark
once we choose to track the overall result.

**Comment by vkargov** [comment]
> we can't (easily) get the data for each single benchmark once we choose to track the overall result
Agreed. I've added the task of adding custom weights to the Trello todo list thing.

**Comment by lewurm** [comment]
thanks!

**Comment by vkargov** [comment]
Updated & rebased this PR.
Added 4 separate benchmark files for the 4 tests, as agreed.

**Pull request merged**
